//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


namespace WeatherDotGov.Types {

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class current_observation {
    
        private string creditField;
    
        private string credit_URLField;
    
        private string suggested_pickupField;
    
        private string suggested_pickup_periodField;
    
        private string locationField;
    
        private string station_idField;
    
        private string latitudeField;
    
        private string longitudeField;
    
        private string observation_timeField;
    
        private string observation_time_rfc822Field;
    
        private string weatherField;
    
        private string temperature_stringField;
    
        private string temp_fField;
    
        private string temp_cField;
    
        private string relative_humidityField;
    
        private string wind_stringField;
    
        private string wind_dirField;
    
        private string wind_degreesField;
    
        private string wind_mphField;
    
        private string wind_gust_mphField;
    
        private string wind_ktField;
    
        private string wind_gust_ktField;
    
        private string pressure_stringField;
    
        private string pressure_mbField;
    
        private string pressure_inField;
    
        private string dewpoint_stringField;
    
        private string dewpoint_fField;
    
        private string dewpoint_cField;
    
        private string windchill_stringField;
    
        private string windchill_fField;
    
        private string windchill_cField;
    
        private string visibility_miField;
    
        private string icon_url_baseField;
    
        private string two_day_history_urlField;
    
        private string icon_url_nameField;
    
        private string ob_urlField;
    
        private string disclaimer_urlField;
    
        private string copyright_urlField;
    
        private string privacy_policy_urlField;
    
        private current_observationImage[] imageField;
    
        private string versionField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string credit_URL {
            get {
                return this.credit_URLField;
            }
            set {
                this.credit_URLField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string suggested_pickup {
            get {
                return this.suggested_pickupField;
            }
            set {
                this.suggested_pickupField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string suggested_pickup_period {
            get {
                return this.suggested_pickup_periodField;
            }
            set {
                this.suggested_pickup_periodField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string station_id {
            get {
                return this.station_idField;
            }
            set {
                this.station_idField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observation_time {
            get {
                return this.observation_timeField;
            }
            set {
                this.observation_timeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observation_time_rfc822 {
            get {
                return this.observation_time_rfc822Field;
            }
            set {
                this.observation_time_rfc822Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string weather {
            get {
                return this.weatherField;
            }
            set {
                this.weatherField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string temperature_string {
            get {
                return this.temperature_stringField;
            }
            set {
                this.temperature_stringField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string temp_f {
            get {
                return this.temp_fField;
            }
            set {
                this.temp_fField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string temp_c {
            get {
                return this.temp_cField;
            }
            set {
                this.temp_cField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string relative_humidity {
            get {
                return this.relative_humidityField;
            }
            set {
                this.relative_humidityField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_string {
            get {
                return this.wind_stringField;
            }
            set {
                this.wind_stringField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_dir {
            get {
                return this.wind_dirField;
            }
            set {
                this.wind_dirField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_degrees {
            get {
                return this.wind_degreesField;
            }
            set {
                this.wind_degreesField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_mph {
            get {
                return this.wind_mphField;
            }
            set {
                this.wind_mphField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_gust_mph {
            get {
                return this.wind_gust_mphField;
            }
            set {
                this.wind_gust_mphField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_kt {
            get {
                return this.wind_ktField;
            }
            set {
                this.wind_ktField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_gust_kt {
            get {
                return this.wind_gust_ktField;
            }
            set {
                this.wind_gust_ktField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pressure_string {
            get {
                return this.pressure_stringField;
            }
            set {
                this.pressure_stringField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pressure_mb {
            get {
                return this.pressure_mbField;
            }
            set {
                this.pressure_mbField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pressure_in {
            get {
                return this.pressure_inField;
            }
            set {
                this.pressure_inField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dewpoint_string {
            get {
                return this.dewpoint_stringField;
            }
            set {
                this.dewpoint_stringField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dewpoint_f {
            get {
                return this.dewpoint_fField;
            }
            set {
                this.dewpoint_fField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dewpoint_c {
            get {
                return this.dewpoint_cField;
            }
            set {
                this.dewpoint_cField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string windchill_string {
            get {
                return this.windchill_stringField;
            }
            set {
                this.windchill_stringField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string windchill_f {
            get {
                return this.windchill_fField;
            }
            set {
                this.windchill_fField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string windchill_c {
            get {
                return this.windchill_cField;
            }
            set {
                this.windchill_cField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string visibility_mi {
            get {
                return this.visibility_miField;
            }
            set {
                this.visibility_miField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icon_url_base {
            get {
                return this.icon_url_baseField;
            }
            set {
                this.icon_url_baseField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string two_day_history_url {
            get {
                return this.two_day_history_urlField;
            }
            set {
                this.two_day_history_urlField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icon_url_name {
            get {
                return this.icon_url_nameField;
            }
            set {
                this.icon_url_nameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ob_url {
            get {
                return this.ob_urlField;
            }
            set {
                this.ob_urlField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string disclaimer_url {
            get {
                return this.disclaimer_urlField;
            }
            set {
                this.disclaimer_urlField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string copyright_url {
            get {
                return this.copyright_urlField;
            }
            set {
                this.copyright_urlField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string privacy_policy_url {
            get {
                return this.privacy_policy_urlField;
            }
            set {
                this.privacy_policy_urlField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("image", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public current_observationImage[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class current_observationImage {
    
        private string urlField;
    
        private string titleField;
    
        private string linkField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
    
        private current_observation[] itemsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("current_observation")]
        public current_observation[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}